source "https://rubygems.org"

gem 'breakpoint'
gem 'mini_magick'
gem 'autoprefixer-rails'
gem 'uglifier'

# Jekyll and Plugins
gem 'jekyll'
gem 'jekyll-archives'
gem 'jekyll-tagging-related_posts'


group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem 'jekyll-assets', github: 'jekyll/jekyll-assets'
   gem 'jekyll-sitemap', github: 'jekyll/jekyll-sitemap'
end

